### ISSUE TITLE
ServiceUnavailable Defunct Connection Address - after a certain period of time

### ISSUE THREAD

**Issue by Zhenshan-Jin** [neo4j/neo4j-python-driver#294]
The neo4j driver will give the error `neobolt.exceptions.ServiceUnavailable: Failed to read from defunct connection Address(host='<remote neo4j bolt>', port=7687)` if certain amount of time spent between the creation of neo4j client and creation of the session. However, if I start the session the second time, the error is gone.

```
from neo4j import GraphDatabase
import time

neo4j_url = "bolt://<remote_neo4j_url>:7687"
user_name = "neo4j"
password = ""
neo4j_client = GraphDatabase.driver(neo4j_url, auth=(user_name, password))

time.sleep(300) # 5 minutes
query = '''MATCH (n) RETURN n LIMIT 1'''

# with error
try:
    with neo4j_client.session() as session:
        query_result = session.run(query)
except Exception as e:
    print(str(e))

# no error
with neo4j_client.session() as session:
    query_result = session.run(query)
```

------------------------
Environment:
python 3.6
neo4j==1.7.2
neobolt==1.7.4
neotime==1.7.4
mac 10.14.4

**Comment by Zhenshan-Jin** [comment]
with the help from this issue, the problem is solved: [#205](https://github.com/neo4j/neo4j-python-driver/issues/205)  
The problem is due that the load balancer in the remote server will kill the idle connections after a while. In my case, it is 4 mins.  
By setting up `max_connection_lifetime=200` it solved my problem:
```
driver = GraphDatabase.driver(uri, auth=(user, password), max_connection_lifetime=200) # 3.33 mins
```

**Comment by carmignanivittorio** [comment]
I am having a similar error, but I could not resolve it with the suggested solution. 
I posted the problem [here](https://stackoverflow.com/questions/59138801/neo4j-connection-closed-after-few-minutes-defunct-connection-address?fbclid=IwAR0DWFng35MMQhTaSixNfAtRCHBSMmL7m476GGnicbFMct8asiWxeD4Dk-s).

I have a server in which the connection is opened (python):

    `self._driver: Driver = GraphDatabase.driver(credentials["uri"], auth=(credentials["user"], credentials["password"]), max_connection_lifetime=3600*24*30, keep_alive=True)`

I run some requests and it works all perfectly. The requests are run by using the function:

```
def __exe_query(self, query: str):
    with self._driver.session() as session:
        session.run(query).consume()
```
Despite these queries do not return anything relevant I added .consume() based on this post https://community.neo4j.com/t/error-while-loading-data-in-neo4j-python-driver/7413/7.

I wait 4-5 minutes (while the server is running waiting for other requests), I run the exact same requests, and I get the error:

`Failed to read from defunct connection Address(host='****', port=**)`

I also tried with `max_connection_lifetime=-1`.

I am working with python 3.7.0 with these libraries versions: neo4j==1.7.2 neobolt==1.7.9 neotime==1.7.4 as suggested by https://github.com/neo4j/neo4j-python-driver/issues/293. It does not work in Win10 and Linux Ubuntu 18.04.3 LTS.

Thanks for your help and attention, Vittorio

**Comment by JnMik** [comment]
Did you guys found the cause of this message ? I have the same.
(Sorry to revive the old thread)

**Comment by carmignanivittorio** [comment]
@JnMik My solution was to use the library of nodejs to connect to the DB and query it from python using gRPC. I do not know if this problem does not exist anymore with more recent updates.

**Comment by rushi47** [comment]
The problem still exists am on python 3.6, and neo4j drive neo4j==4.1.1.
```
Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))
Transaction failed and will be retried in 1.9554626137792632s (Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687))))
```
I have my connection configured as below :
```
    def __init__(self):
        self.uri = "neo4j://localhost:7687"      
        self.neo_con = GraphDatabase.driver(self.uri, auth=("neo4j", "test"), max_connection_lifetime=200) 
```
Please let me know if anyone finds the solution to problem, cause exception handling is tricky because of this.

Thanks a lot

**Comment by carmignanivittorio** [comment]
> The problem still exists am on python 3.6, and neo4j drive neo4j==4.1.1.
> 
> ```
> Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687)))
> Transaction failed and will be retried in 1.9554626137792632s (Failed to read from defunct connection IPv4Address(('localhost', 7687)) (IPv4Address(('127.0.0.1', 7687))))
> ```
> 
> I have my connection configured as below :
> 
> ```
>     def __init__(self):
>         self.uri = "neo4j://localhost:7687"      
>         self.neo_con = GraphDatabase.driver(self.uri, auth=("neo4j", "test"), max_connection_lifetime=200) 
> ```
> 
> Please let me know if anyone finds the solution to problem, cause exception handling is tricky because of this.
> 
> Thanks a lot

I Retried with the new version of neo4j python library but I still have the same problem.

**Comment by heiqs** [comment]
The very same problem as others with 4.1.1 driver

**Comment by direncuyanik** [comment]
Same problem in 4.2.0

**Comment by MS-AvivG** [comment]
Same in 4.2.1

**Comment by amikrop** [comment]
Same in neo4j-driver==4.3.6 neobolt==1.7.17

**Comment by robsdedude** [comment]
Firstly, neobolt is not a dependency of the driver anymore. I don't know when that was changed but 4.0+ don't need it for sure.

Secondly, as written by Zhenshan-Jin 

> The problem is due that the load balancer in the remote server will kill the idle connections after a while.

There is nothing much the driver can do about a unexpectedly closed connection. There are two workarounds provided by the driver for you to use.

1. Use the config `max_connection_lifetime` (in seconds) and set it to something shorter than the expected lifetime of connections. This setting will make the driver ignore all connections that have been idling in the pool for longer than `max_connection_lifetime` and close them without trying to use them.
2. Use [transaction functions](https://neo4j.com/docs/api/python-driver/4.3/api.html#managed-transactions-transaction-functions). With them, the driver will retry running the workload if it encounters this error. However, this incorporates an exponential back-off (i.e., the driver will wait longer between retries every time). So this is the more robust but less perfomant solution.

Ideally, you make use of both.

**EDIT**: There is a minor mistake in 1. It should be:  
This setting will make the driver ignore all connections *(while acquiring a new connection from the pool)* that have *existed* in the pool for longer than `max_connection_lifetime` and close them without trying to use them.
